"""
retriever.py — Hybrid retrieval system using Pinecone sparse-dense index.

Provides the HybridRetriever class, which handles:
  - Building Pinecone hybrid index (dense + sparse vectors)
  - BM25 sparse vectors via pinecone-text BM25Encoder
  - Alpha-based fusion (Pinecone handles internally)
  - Optional user-chosen document-type filter
"""

import os
import numpy as np
from typing import List, Tuple, Optional, Dict, Union
from pinecone import Pinecone
from pinecone_text.sparse import BM25Encoder

from core.models import ChunkMetadata, SearchConfig
from llm.llm_router import EMBED_DIM


class HybridRetriever:
    """
    Hybrid retrieval system using Pinecone's sparse-dense index.

    Combines:
    1. Dense vector search (semantic similarity) via Pinecone
    2. BM25 sparse vector search (lexical matching) via Pinecone
    3. Alpha-based fusion (Pinecone handles internally)
    4. Optional metadata filter when the caller names a document type

    Architecture:
    - Dense vectors: Gemini embeddings (see llm/llm_router.py)
    - Sparse vectors: Generated by BM25Encoder from pinecone-text
    - Both stored together in a single Pinecone hybrid index
    - Optional metadata filtering by document type, when the caller asks

    Two stages were built, measured and removed. Neither is coming back
    without new evidence; see upgrade_roadmap.txt.

    - **No cross-encoder reranking.** Measured on 250 questions: it changed
      answer quality by a statistically indistinguishable amount.
    - **No automatic query routing.** Doc-type centroids (the mean of every
      chunk in a type) were used to guess which document a question belonged
      to. A mean over a heterogeneous type — legal descriptions, wire
      instructions and tax notes in one Preliminary Title Report —
      represents no real document, so the similarity it produces is not
      trustworthy. It was also, unintentionally, ablated: a fetch bug left
      routing dead on every rehydrated session and answers stayed correct.
      Queries now search the whole namespace, which is what recall@5 = 0.964
      was already telling us was sufficient.
    """

    def __init__(self, namespace: str, chat_id: str, alpha: float = 0.5):
        """
        Initialize the Pinecone hybrid retriever.

        Args:
            namespace: the OWNER's namespace — one per user, holding every
                       chat that user has. User-to-user isolation is
                       structural: a query cannot reach another namespace.
            chat_id:   which chat inside that namespace. Every vector id is
                       prefixed `{chat_id}#` and carries chat_id in metadata,
                       so a chat can be listed and deleted by prefix (Pinecone
                       has no delete-by-filter) and queries can be scoped to
                       one chat.
            alpha: Balance between dense (1.0) and sparse (0.0) search
        """
        # Hybrid search parameter
        self.alpha = alpha  # 1.0 = pure semantic, 0.0 = pure keyword

        # Pinecone Setup
        pinecone_api_key = os.getenv("PINECONE_API_KEY")
        pinecone_index_name = os.getenv("PINECONE_INDEX_NAME")
        pinecone_host = os.getenv("PINECONE_HOST")
        self.namespace = namespace
        self.chat_id = chat_id
        self.id_prefix = f"{chat_id}#"

        if not all([pinecone_api_key, pinecone_index_name, pinecone_host]):
            print("⚠️ PINECONE_API_KEY, PINECONE_INDEX_NAME, PINECONE_HOST must be set in .env for Pinecone retrieval.")
            self.pc_index = None
        else:
            pc = Pinecone(api_key=pinecone_api_key)
            self.pc_index = pc.Index(pinecone_index_name, host=pinecone_host)
            self._assert_index_compatible(pc, pinecone_index_name)
            print(f"✅ Pinecone index '{pinecone_index_name}' [namespace: {self.namespace}] configured successfully.")

        # BM25 encoder for sparse vectors
        self.bm25_encoder = BM25Encoder()

        # Local storage for metadata
        self.chunks_metadata: List[ChunkMetadata] = []

        # Embedding model reference (set during build or rehydrate)
        self.embed_model = None

        # Corpus size, tracked explicitly because a rehydrated retriever has
        # no local chunk list. Display only.
        self.chunk_count: int = 0

    def _assert_index_compatible(self, pc, index_name: str):
        """
        Fail at session start, not after a full extraction run.

        A dimension or metric mismatch only surfaces at the upsert call, which
        happens after Docling, after one LLM call per page and one embedding
        call per chunk — minutes of work and real API spend, thrown away for a
        config error that is knowable up front.
        """
        try:
            spec = pc.describe_index(index_name)
        except Exception as e:
            print(f"⚠️ Could not describe index '{index_name}': {type(e).__name__}: {e}")
            return

        if spec.dimension != EMBED_DIM:
            raise ValueError(
                f"Pinecone index '{index_name}' has dimension {spec.dimension}, "
                f"but embeddings are {EMBED_DIM}-dimensional. Recreate the index "
                f"with dimension={EMBED_DIM} and metric='dotproduct'."
            )
        if spec.metric != "dotproduct":
            raise ValueError(
                f"Pinecone index '{index_name}' uses metric '{spec.metric}'. "
                f"Sparse-dense hybrid search requires metric='dotproduct'."
            )

    def _list_chat_ids(self) -> List[str]:
        """
        Every vector id belonging to this chat.

        index.list() yields one ListResponse per PAGE, each holding .vectors of
        ListItem, each with .id. Treating a page as an id gives you exactly one
        bogus "id" per page and a delete that silently removes nothing.
        """
        ids: List[str] = []
        for page in self.pc_index.list(prefix=self.id_prefix,
                                       namespace=self.namespace):
            for item in getattr(page, "vectors", page) or []:
                ids.append(getattr(item, "id", item))
        return ids

    def delete_chat(self):
        """
        Delete only this chat's vectors, leaving the rest of the namespace.

        Pinecone deletion is id-only — it does not accept a metadata filter —
        so the ids are listed by prefix first. That is the reason vector ids
        carry `{chat_id}#`.
        """
        if self.pc_index is None:
            return
        try:
            ids = self._list_chat_ids()
            for i in range(0, len(ids), 1000):
                self.pc_index.delete(ids=ids[i:i + 1000], namespace=self.namespace)
            print(f"🧹 Deleted {len(ids)} vectors for chat '{self.chat_id}'.")
        except Exception as e:
            # A chat that was never indexed has nothing to delete; anything
            # else is worth seeing but must not break teardown.
            print(f"ℹ️ Could not delete chat '{self.chat_id}': "
                  f"{type(e).__name__}: {e}")

    def delete_namespace(self):
        """Delete every chat in this namespace. Used when an account goes."""
        if self.pc_index is None:
            return
        try:
            self.pc_index.delete_namespace(name=self.namespace)
            print(f"🧹 Deleted Pinecone namespace '{self.namespace}'.")
        except Exception as e:
            print(f"ℹ️ Could not delete namespace '{self.namespace}': "
                  f"{type(e).__name__}: {e}")

    # -----------------------------------------------------------------------
    # Index Building
    # -----------------------------------------------------------------------

    def build_indices(self, chunks_metadata: List[ChunkMetadata], embed_model):
        """
        Build Pinecone hybrid index with dense + sparse vectors.
        Upserts into existing Pinecone index.

        Args:
            chunks_metadata: List of ChunkMetadata objects
            embed_model: SentenceTransformer model for dense embeddings
        """
        if not self.pc_index:
            raise ValueError("Pinecone index not configured. Check .env variables.")

        print("🔨 Building Pinecone hybrid index...")

        self.chunks_metadata = chunks_metadata
        self.embed_model = embed_model

        # === Step 1: Compute Dense Embeddings ===
        print("  📊 Computing dense embeddings...")
        texts = [chunk.text for chunk in chunks_metadata]
        dense_embeddings = embed_model.encode(
            texts, show_progress_bar=True, task_type="RETRIEVAL_DOCUMENT"
        )
        dense_embeddings = np.array(dense_embeddings).astype('float32')

        doc_types = set(chunk.doc_type for chunk in chunks_metadata)

        # === Step 2: Fit BM25 Encoder on corpus ===
        # IDF is corpus-specific, so this encoder may only query the namespace
        # it was fitted on.
        print("  📝 Fitting BM25 encoder on corpus...")
        self.bm25_encoder.fit(texts)
        print("  ✅ BM25 encoder fitted")

        # === Step 4: Generate Sparse Vectors ===
        print("  📝 Generating sparse vectors...")
        sparse_vectors = [self.bm25_encoder.encode_documents(text) for text in texts]

        # === Step 5: Upsert dense + sparse vectors into Pinecone ===
        print(f"  📤 Upserting vectors into Pinecone [namespace: {self.namespace}]...")
        batch_size = 100

        for i in range(0, len(chunks_metadata), batch_size):
            batch_end = min(i + batch_size, len(chunks_metadata))
            vectors_to_upsert = []

            for j in range(i, batch_end):
                chunk = chunks_metadata[j]

                # Normalize dense vector for dotproduct
                dense_vec = dense_embeddings[j].copy()
                norm = np.linalg.norm(dense_vec)
                if norm > 0:
                    dense_vec = dense_vec / norm

                vectors_to_upsert.append({
                    # chunk_id is only unique within a document, so it is
                    # prefixed with the chat to stay unique in a namespace
                    # shared by all of this user's chats.
                    "id": f"{self.id_prefix}{chunk.chunk_id}",
                    "values": dense_vec.tolist(),
                    "sparse_values": sparse_vectors[j],
                    "metadata": {
                        "chat_id": self.chat_id,
                        "text": chunk.text,
                        "doc_type": chunk.doc_type,
                        "doc_id": chunk.doc_id,
                        "filename": chunk.filename,
                        "chunk_index": chunk.chunk_index,
                        "page_start": chunk.page_start,
                        "page_end": chunk.page_end
                    }
                })

            self.pc_index.upsert(vectors=vectors_to_upsert, namespace=self.namespace)

            if (i // batch_size) % 5 == 0:
                print(f"    Upserted {batch_end}/{len(chunks_metadata)} vectors...")

        self.chunk_count = len(chunks_metadata)

        print(f"✅ Indexed {len(chunks_metadata)} chunks across {len(doc_types)} document types")
        print(f"   Alpha={self.alpha}")

    # -----------------------------------------------------------------------
    # Persistence / Rehydration
    # -----------------------------------------------------------------------

    def export_bm25_params(self) -> Dict:
        """The fitted BM25 encoder, as a JSON-serialisable dict.

        BM25 scores are only comparable against vectors written by the *same*
        fitted encoder. Persisting this is what lets a session survive a restart
        with its sparse half intact instead of silently degrading to dense-only.
        """
        return self.bm25_encoder.get_params()

    def rehydrate(self, bm25_params: Dict, embed_model,
                  chunk_count: int = 0) -> None:
        """
        Restore a retriever for a chat indexed in an earlier process, without
        re-ingesting the document.

        Everything needed to *search* already lives in Pinecone; the only
        genuinely unrecoverable state is the fitted BM25 encoder, which is
        passed back in from Postgres.
        """
        self.embed_model = embed_model
        self.bm25_encoder.set_params(**bm25_params)
        self._load_corpus_shape_from_index(chunk_count)

    def _load_corpus_shape_from_index(self, chunk_count: int = 0) -> None:
        """
        Set this chat's vector count.

        Taken from Postgres, not from describe_index_stats: the namespace now
        holds every chat this user owns, so its total says nothing about one
        chat. Only counted by listing ids when Postgres has no figure.

        The count is display only, so a failure here must not break the query.
        """
        if chunk_count:
            self.chunk_count = chunk_count
            print(f"♻️ Rehydrated chat '{self.chat_id}': {chunk_count} chunks")
            return
        if self.pc_index is None:
            return
        try:
            self.chunk_count = len(self._list_chat_ids())
            if self.chunk_count:
                print(f"♻️ Rehydrated chat '{self.chat_id}': {self.chunk_count} chunks")
            else:
                print(f"⚠️ Chat '{self.chat_id}' has no vectors in '{self.namespace}'.")
        except Exception as e:
            print(f"ℹ️ Could not count vectors for '{self.chat_id}': "
                  f"{type(e).__name__}: {e}")

    # -----------------------------------------------------------------------
    # Search scope
    # -----------------------------------------------------------------------

    def _resolve_search_config(self, filter_doc_type: Optional[str]) -> SearchConfig:
        """
        Decide the search scope. Only the caller can narrow it.

        There is no automatic routing: a query searches the whole namespace
        unless the user explicitly picked a document type in the UI. Guessing
        the type from a centroid was removed — see the class docstring.
        """
        if filter_doc_type:
            print(f"🔍 Using explicit filter: {filter_doc_type}")
            return SearchConfig(
                use_filtered=True,
                selected_type=filter_doc_type,
                total_chunks=self.chunk_count,
                routing_info={'method': 'user_filter', 'type': filter_doc_type},
            )

        return SearchConfig(
            use_filtered=False,
            selected_type=None,
            total_chunks=self.chunk_count,
            routing_info={'method': 'full_search'},
        )

    # -----------------------------------------------------------------------
    # Hybrid Search via Pinecone
    # -----------------------------------------------------------------------

    def _scale_vectors(self, dense_vec: List[float], sparse_vec: Dict) -> Tuple[List[float], Dict]:
        """
        Scale dense and sparse vectors using alpha for hybrid search.

        alpha = 1.0 → pure semantic
        alpha = 0.0 → pure keyword
        alpha = 0.5 → equal weight
        """
        scaled_dense = [v * self.alpha for v in dense_vec]

        scaled_sparse = {
            "indices": sparse_vec["indices"],
            "values": [v * (1 - self.alpha) for v in sparse_vec["values"]]
        }

        return scaled_dense, scaled_sparse

    def _query_pinecone(self, query: str, top_k: int,
                         filter_doc_type: Optional[str] = None) -> List[Dict]:
        """
        Query Pinecone hybrid index with both dense and sparse vectors.
        Single API call — Pinecone searches dense + sparse and fuses internally.
        """
        # Generate dense query vector
        query_dense = np.asarray(
            self.embed_model.encode([query], task_type="RETRIEVAL_QUERY")[0],
            dtype='float32',
        )
        norm = np.linalg.norm(query_dense)
        if norm > 0:
            query_dense = query_dense / norm

        # Generate sparse query vector
        query_sparse = self.bm25_encoder.encode_queries(query)

        # Scale vectors using alpha
        scaled_dense, scaled_sparse = self._scale_vectors(
            query_dense.tolist(), query_sparse
        )

        # The chat filter is not optional and is applied here rather than by
        # callers, because the namespace holds every chat this user owns and a
        # forgotten filter would answer from the wrong document.
        query_filter = {"chat_id": {"$eq": self.chat_id}}
        if filter_doc_type:
            query_filter["doc_type"] = {"$eq": filter_doc_type}

        query_params = {
            "vector": scaled_dense,
            "sparse_vector": scaled_sparse,
            "top_k": top_k,
            "include_metadata": True,
            "namespace": self.namespace,
            "filter": query_filter,
        }

        results = self.pc_index.query(**query_params)

        return results.get("matches", [])

    @staticmethod
    def _match_to_chunk(match: Dict) -> ChunkMetadata:
        """
        Rebuild a ChunkMetadata from a Pinecone match.

        build_indices stores every field this needs on the vector itself, so a
        match is self-describing and retrieval never has to consult local
        state. Pinecone returns numeric metadata as floats, hence the int()s.
        """
        md = match.get("metadata") or {}
        return ChunkMetadata(
            chunk_id=match["id"],
            doc_id=md.get("doc_id", "unknown"),
            doc_type=md.get("doc_type", "Other"),
            filename=md.get("filename", "unknown"),
            chunk_index=int(md.get("chunk_index", 0)),
            page_start=int(md.get("page_start", 0)),
            page_end=int(md.get("page_end", 0)),
            text=md.get("text", ""),
        )

    # -----------------------------------------------------------------------
    # Main Retrieve Method
    # -----------------------------------------------------------------------

    def retrieve(self, query: str, k: int = 6,
                 filter_doc_type: Optional[str] = None,
                 return_details: bool = False) -> Union[List[Tuple], Dict]:
        """
        Retrieve relevant chunks using Pinecone hybrid search.

        The query is embedded and matched against every chunk in the namespace.
        Nothing narrows that scope unless the caller passes filter_doc_type.

        Args:
            query: Search query
            k: Number of results to return
            filter_doc_type: Optional user-chosen document type filter
            return_details: Whether to return detailed result info

        Returns:
            List of (ChunkMetadata, score) tuples, or detailed dict
        """
        if self.pc_index is None:
            raise ValueError("No index connected. Check your Pinecone .env variables.")

        # === Step 1: Scope ===
        config = self._resolve_search_config(filter_doc_type)
        scope = config.selected_type if config.use_filtered else "all chunks"
        print(f"📊 Searching {scope} of {config.total_chunks} (alpha={self.alpha})")

        # === Step 2: Query Pinecone (single API call) ===
        # Whole namespace unless the user picked a type. An explicit filter is
        # honoured rather than silently widened.
        matches = self._query_pinecone(
            query=query,
            top_k=k,
            filter_doc_type=config.selected_type if config.use_filtered else None
        )

        # === Step 3: Rebuild ChunkMetadata from what Pinecone returned ===
        # Rebuilt from the vector's own metadata, so nothing is silently
        # dropped for being absent from a local list.
        results = [(self._match_to_chunk(m), m["score"]) for m in matches]

        if not results:
            print("⚠️ No results found")
            if return_details:
                return {'results': [], 'routing_info': config.routing_info, 'query': query}
            return []

        # === Step 5: Return results ===
        results = results[:k]

        if not return_details:
            return results

        detailed_results = []
        for chunk, final_score in results:
            detailed_results.append({
                'chunk': chunk,
                'chunk_index': chunk.chunk_index,
                'final_score': final_score,
                'doc_type': chunk.doc_type,
                'pages': f"{chunk.page_start}-{chunk.page_end}",
            })

        return {
            'results': detailed_results,
            'routing_info': config.routing_info,
            'config': {
                'alpha': self.alpha,
            },
            'retrieval_stats': {
                'total_chunks': config.total_chunks,
                'final_returned': len(detailed_results)
            },
            'query': query
        }
