"""
retriever.py — Hybrid retrieval system using Pinecone sparse-dense index.

Provides the HybridRetriever class, which handles:
  - Building Pinecone hybrid index (dense + sparse vectors)
  - BM25 sparse vectors via pinecone-text BM25Encoder
  - Alpha-based fusion (Pinecone handles internally)
  - Embedding centroid classification for auto-routing (no LLM needed)
  - Fallback to full-search when filtered results are weak
  - Optional reranking via Modal-hosted BAAI/bge-reranker-base
"""

import os
import numpy as np
from typing import List, Tuple, Optional, Dict, Union
from pinecone import Pinecone
from pinecone_text.sparse import BM25Encoder

from core.models import ChunkMetadata, SearchConfig


class HybridRetriever:
    """
    Hybrid retrieval system using Pinecone's sparse-dense index.

    Combines:
    1. Dense vector search (semantic similarity) via Pinecone
    2. BM25 sparse vector search (lexical matching) via Pinecone
    3. Alpha-based fusion (Pinecone handles internally)
    4. Embedding centroid classification for document-type routing (no LLM)
    5. Optional reranking via Modal-hosted BAAI/bge-reranker-base

    Architecture:
    - Dense vectors: Generated by SentenceTransformer (e.g., BAAI/bge-small-en-v1.5)
    - Sparse vectors: Generated by BM25Encoder from pinecone-text
    - Both stored together in a single Pinecone hybrid index
    - Query routing via centroid classification + metadata filtering
    - Reranking via Modal-hosted BAAI/bge-reranker-base
    """

    def __init__(self,
                 alpha: float = 0.5,
                 use_rerank: bool = False,
                 margin_threshold: float = 0.08,
                 fallback_score_threshold: float = 0.3):
        """
        Initialize the Pinecone hybrid retriever.

        Args:
            alpha: Balance between dense (1.0) and sparse (0.0) search
            use_rerank: Whether to use cross-encoder reranking
            margin_threshold: Min margin for centroid routing confidence
            fallback_score_threshold: If filtered search is weak, fallback to all
        """
        # Hybrid search parameter
        self.alpha = alpha  # 1.0 = pure semantic, 0.0 = pure keyword

        # Centroid classification parameters
        self.margin_threshold = margin_threshold
        self.fallback_score_threshold = fallback_score_threshold

        # Reranking configuration
        self.use_rerank = use_rerank
        self.reranker = None
        if self.use_rerank:
            self._load_reranker()

        # Pinecone Setup
        pinecone_api_key = os.getenv("PINECONE_API_KEY")
        pinecone_index_name = os.getenv("PINECONE_INDEX_NAME")
        pinecone_host = os.getenv("PINECONE_HOST")
        self.namespace = "mortgage_namespace"

        if not all([pinecone_api_key, pinecone_index_name, pinecone_host]):
            print("⚠️ PINECONE_API_KEY, PINECONE_INDEX_NAME, PINECONE_HOST must be set in .env for Pinecone retrieval.")
            self.pc_index = None
        else:
            pc = Pinecone(api_key=pinecone_api_key)
            self.pc_index = pc.Index(pinecone_index_name, host=pinecone_host)
            print(f"✅ Pinecone index '{pinecone_index_name}' [namespace: {self.namespace}] configured successfully.")

        # BM25 encoder for sparse vectors
        self.bm25_encoder = BM25Encoder()

        # Local storage for metadata
        self.chunks_metadata: List[ChunkMetadata] = []

        # Centroid vectors for document-type classification
        self.doc_type_centroids: Dict[str, np.ndarray] = {}

        # Embedding model reference (set during build)
        self.embed_model = None

    def clear(self):
        """Reset local state. Persistence in Pinecone remains."""
        print("🧹 Clearing local indices (Pinecone persistence remains).")
        self.chunks_metadata = []
        self.doc_type_centroids = {}
        self.embed_model = None

    # -----------------------------------------------------------------------
    # Reranker Initialisation
    # -----------------------------------------------------------------------

    def _load_reranker(self):
        """
        Set up the reranker via Modal HTTP endpoint.

        Requires RERANKER_URL env var pointing to the Modal-deployed
        BAAI/bge-reranker-base service.
        """
        import os
        modal_url = os.getenv("RERANKER_URL", "").strip()

        if modal_url:
            print(f"🌐 Using Modal reranker endpoint: {modal_url}")
            self.reranker = modal_url
        else:
            print("⚠️ RERANKER_URL not set. Reranking disabled.")
            self.use_rerank = False
            self.reranker = None

    def set_rerank(self, use_rerank: bool):
        """Enable or disable reranking."""
        if use_rerank and not self.reranker:
            self.use_rerank = True
            self._load_reranker()
        elif not use_rerank:
            self.use_rerank = False
            print("🔄 Reranking disabled")
        else:
            self.use_rerank = True
            print("✅ Reranking enabled (Modal endpoint)")

    # -----------------------------------------------------------------------
    # Index Building
    # -----------------------------------------------------------------------

    def build_indices(self, chunks_metadata: List[ChunkMetadata], embed_model):
        """
        Build Pinecone hybrid index with dense + sparse vectors.
        Upserts into existing Pinecone index.

        Args:
            chunks_metadata: List of ChunkMetadata objects
            embed_model: SentenceTransformer model for dense embeddings
        """
        if not self.pc_index:
            raise ValueError("Pinecone index not configured. Check .env variables.")

        rerank_status = "enabled" if self.use_rerank else "disabled"
        print(f"🔨 Building Pinecone hybrid index (rerank: {rerank_status})...")

        self.chunks_metadata = chunks_metadata
        self.embed_model = embed_model

        # === Step 1: Compute Dense Embeddings ===
        print("  📊 Computing dense embeddings...")
        texts = [chunk.text for chunk in chunks_metadata]
        dense_embeddings = embed_model.encode(texts, show_progress_bar=True)
        dense_embeddings = np.array(dense_embeddings).astype('float32')

        # Store embeddings in metadata for centroid use
        for i, chunk in enumerate(chunks_metadata):
            chunk.embedding = dense_embeddings[i].copy()

        # === Step 2: Build Centroid Vectors for Query Routing ===
        print("  🎯 Computing document-type centroids...")
        doc_types = set(chunk.doc_type for chunk in chunks_metadata)

        for doc_type in doc_types:
            type_indices = [i for i, chunk in enumerate(chunks_metadata)
                           if chunk.doc_type == doc_type]
            if type_indices:
                type_embeddings = dense_embeddings[type_indices]
                centroid = type_embeddings.mean(axis=0)
                norm = np.linalg.norm(centroid)
                if norm > 0:
                    centroid = centroid / norm
                self.doc_type_centroids[doc_type] = centroid

        print(f"  ✅ Built {len(self.doc_type_centroids)} document-type centroids")

        # === Step 3: Fit BM25 Encoder on corpus ===
        print("  📝 Fitting BM25 encoder on corpus...")
        self.bm25_encoder.fit(texts)
        print("  ✅ BM25 encoder fitted")

        # === Step 4: Generate Sparse Vectors ===
        print("  📝 Generating sparse vectors...")
        sparse_vectors = [self.bm25_encoder.encode_documents(text) for text in texts]

        # === Step 5: Upsert dense + sparse vectors into Pinecone ===
        print(f"  📤 Upserting vectors into Pinecone [namespace: {self.namespace}]...")
        batch_size = 100

        for i in range(0, len(chunks_metadata), batch_size):
            batch_end = min(i + batch_size, len(chunks_metadata))
            vectors_to_upsert = []

            for j in range(i, batch_end):
                chunk = chunks_metadata[j]

                # Normalize dense vector for dotproduct
                dense_vec = dense_embeddings[j].copy()
                norm = np.linalg.norm(dense_vec)
                if norm > 0:
                    dense_vec = dense_vec / norm

                vectors_to_upsert.append({
                    "id": chunk.chunk_id,
                    "values": dense_vec.tolist(),
                    "sparse_values": sparse_vectors[j],
                    "metadata": {
                        "text": chunk.text,
                        "doc_type": chunk.doc_type,
                        "doc_id": chunk.doc_id,
                        "filename": chunk.filename,
                        "chunk_index": chunk.chunk_index,
                        "page_start": chunk.page_start,
                        "page_end": chunk.page_end
                    }
                })

            self.pc_index.upsert(vectors=vectors_to_upsert, namespace=self.namespace)

            if (i // batch_size) % 5 == 0:
                print(f"    Upserted {batch_end}/{len(chunks_metadata)} vectors...")

        print(f"✅ Indexed {len(chunks_metadata)} chunks across {len(doc_types)} document types")
        print(f"   Alpha={self.alpha}, margin_threshold={self.margin_threshold}")

    # -----------------------------------------------------------------------
    # Centroid Classification
    # -----------------------------------------------------------------------

    def _classify_by_centroid(self, query: str) -> Tuple[Optional[str], float, Dict]:
        """
        Classify query to a document type using embedding centroid similarity.
        """
        if not self.doc_type_centroids:
            return None, 0.0, {'method': 'no_centroids'}

        query_embedding = self.embed_model.encode([query])[0].astype('float32')
        query_norm = np.linalg.norm(query_embedding)
        if query_norm > 0:
            query_embedding = query_embedding / query_norm

        scores = {}
        for doc_type, centroid in self.doc_type_centroids.items():
            scores[doc_type] = float(np.dot(query_embedding, centroid))

        sorted_types = sorted(scores.items(), key=lambda x: x[1], reverse=True)

        best_type = sorted_types[0][0]
        best_score = sorted_types[0][1]

        if len(sorted_types) >= 2:
            margin = best_score - sorted_types[1][1]
        else:
            margin = best_score

        routing_info = {
            'method': 'centroid',
            'predicted_type': best_type,
            'best_score': round(best_score, 4),
            'margin': round(margin, 4),
            'top_3': [(t, round(s, 4)) for t, s in sorted_types[:3]]
        }

        print(f"🎯 Centroid classification: {best_type} "
              f"(score: {best_score:.4f}, margin: {margin:.4f})")

        return best_type, margin, routing_info

    # -----------------------------------------------------------------------
    # Query Routing
    # -----------------------------------------------------------------------

    def _resolve_search_config(self, query: str,
                                filter_doc_type: Optional[str],
                                auto_route: bool,
                                confidence_threshold: float) -> SearchConfig:
        """Determine search parameters using centroid classification."""
        use_filtered = False
        selected_type = None
        routing_info = {'method': 'full_search'}

        # Priority 1: Explicit filter
        if filter_doc_type:
            use_filtered = True
            selected_type = filter_doc_type
            routing_info = {'method': 'filter', 'type': filter_doc_type}
            print(f"🔍 Using explicit filter: {filter_doc_type}")

        # Priority 2: Auto-route using centroid classification
        elif auto_route and self.doc_type_centroids:
            predicted_type, margin, centroid_info = self._classify_by_centroid(query)
            routing_info = centroid_info

            if margin >= self.margin_threshold:
                use_filtered = True
                selected_type = predicted_type
                print(f"✅ Centroid routing to: {predicted_type} (margin: {margin:.4f})")
            else:
                print(f"⚠️ Low margin ({margin:.4f} < {self.margin_threshold}), "
                      f"searching all chunks")

        total_chunks = sum(1 for c in self.chunks_metadata
                          if c.doc_type == selected_type) if use_filtered else len(self.chunks_metadata)

        return SearchConfig(
            use_filtered=use_filtered,
            selected_type=selected_type,
            total_chunks=total_chunks,
            routing_info=routing_info
        )

    # -----------------------------------------------------------------------
    # Hybrid Search via Pinecone
    # -----------------------------------------------------------------------

    def _scale_vectors(self, dense_vec: List[float], sparse_vec: Dict) -> Tuple[List[float], Dict]:
        """
        Scale dense and sparse vectors using alpha for hybrid search.

        alpha = 1.0 → pure semantic
        alpha = 0.0 → pure keyword
        alpha = 0.5 → equal weight
        """
        scaled_dense = [v * self.alpha for v in dense_vec]

        scaled_sparse = {
            "indices": sparse_vec["indices"],
            "values": [v * (1 - self.alpha) for v in sparse_vec["values"]]
        }

        return scaled_dense, scaled_sparse

    def _query_pinecone(self, query: str, top_k: int,
                         filter_doc_type: Optional[str] = None) -> List[Dict]:
        """
        Query Pinecone hybrid index with both dense and sparse vectors.
        Single API call — Pinecone searches dense + sparse and fuses internally.
        """
        # Generate dense query vector
        query_dense = self.embed_model.encode([query])[0].astype('float32')
        norm = np.linalg.norm(query_dense)
        if norm > 0:
            query_dense = query_dense / norm

        # Generate sparse query vector
        query_sparse = self.bm25_encoder.encode_queries(query)

        # Scale vectors using alpha
        scaled_dense, scaled_sparse = self._scale_vectors(
            query_dense.tolist(), query_sparse
        )

        # Build query params
        query_params = {
            "vector": scaled_dense,
            "sparse_vector": scaled_sparse,
            "top_k": top_k,
            "include_metadata": True,
            "namespace": self.namespace,
        }

        # Add metadata filter if routing to specific doc type
        if filter_doc_type:
            query_params["filter"] = {"doc_type": {"$eq": filter_doc_type}}

        results = self.pc_index.query(**query_params)

        return results.get("matches", [])

    # -----------------------------------------------------------------------
    # Reranking
    # -----------------------------------------------------------------------

    def _rerank_results(self, query: str, results: List[Tuple],
                        top_k: int = None) -> List[Tuple]:
        """
        Rerank candidates via Modal-hosted BAAI/bge-reranker-base.

        Args:
            results: List of (chunk_idx, ChunkMetadata, score) tuples
        """
        if not self.use_rerank or not self.reranker or not results:
            return results

        texts = [chunk.text for _, chunk, _ in results]
        print(f"🔄 Reranking {len(results)} results via Modal...")

        try:
            import requests
            resp = requests.post(
                f"{self.reranker}/rerank",
                json={"query": query, "texts": texts},
                timeout=60,
            )
            resp.raise_for_status()
            rerank_scores = resp.json()["scores"]
        except Exception as e:
            print(f"⚠️ Reranking failed ({e}), returning original order")
            return results[:top_k] if top_k else results

        # Normalise to [score_floor, 1.0]
        score_floor = 0.05
        min_score = min(rerank_scores)
        max_score = max(rerank_scores)

        if max_score > min_score:
            normalized_scores = [
                score_floor + (1.0 - score_floor) * (s - min_score) / (max_score - min_score)
                for s in rerank_scores
            ]
        else:
            normalized_scores = [1.0] * len(rerank_scores)

        reranked = [(idx, chunk, float(ns))
                    for (idx, chunk, _), ns in zip(results, normalized_scores)]
        reranked.sort(key=lambda x: x[2], reverse=True)

        if top_k:
            reranked = reranked[:top_k]

        print(f"✅ Reranking complete. Top score: {reranked[0][2]:.4f}")
        return reranked

    # -----------------------------------------------------------------------
    # Main Retrieve Method
    # -----------------------------------------------------------------------

    def retrieve(self, query: str, k: int = 4,
                 filter_doc_type: Optional[str] = None,
                 auto_route: bool = False,
                 return_details: bool = False,
                 confidence_threshold: float = 0.7) -> Union[List[Tuple], Dict]:
        """
        Retrieve relevant chunks using Pinecone hybrid search.

        Args:
            query: Search query
            k: Number of results to return
            filter_doc_type: Explicit document type filter
            auto_route: Whether to auto-detect doc type via centroids
            return_details: Whether to return detailed result info
            confidence_threshold: Legacy param (margin_threshold is used instead)

        Returns:
            List of (ChunkMetadata, score) tuples, or detailed dict
        """
        if self.pc_index is None:
            raise ValueError("No index connected. Check your Pinecone .env variables.")

        # === Step 1: Query Routing ===
        config = self._resolve_search_config(
            query, filter_doc_type, auto_route, confidence_threshold
        )
        print(f"📊 Searching {config.total_chunks} chunks (alpha={self.alpha})")

        # === Step 2: Determine how many to retrieve (more if reranking) ===
        retrieve_k = k * 3 if self.use_rerank else k

        # === Step 3: Query Pinecone (single API call) ===
        matches = self._query_pinecone(
            query=query,
            top_k=retrieve_k,
            filter_doc_type=config.selected_type if config.use_filtered else None
        )

        # === Step 4: Fallback if filtered results are weak ===
        if matches and config.use_filtered:
            top_score = matches[0]["score"] if matches else 0
            if top_score < self.fallback_score_threshold:
                print(f"⚠️ Filtered top score ({top_score:.4f}) below threshold, "
                      f"falling back to full search")
                config = SearchConfig(
                    use_filtered=False,
                    selected_type=None,
                    total_chunks=len(self.chunks_metadata),
                    routing_info={
                        'method': 'fallback',
                        'original': config.routing_info,
                        'reason': f'top_score {top_score:.4f} < {self.fallback_score_threshold}'
                    }
                )
                matches = self._query_pinecone(
                    query=query,
                    top_k=retrieve_k,
                    filter_doc_type=None
                )

        # === Step 5: Map Pinecone results back to ChunkMetadata ===
        chunk_lookup = {chunk.chunk_id: (i, chunk)
                        for i, chunk in enumerate(self.chunks_metadata)}

        results = []
        for match in matches:
            chunk_id = match["id"]
            score = match["score"]
            if chunk_id in chunk_lookup:
                idx, chunk = chunk_lookup[chunk_id]
                results.append((idx, chunk, score))

        if not results:
            print("⚠️ No results found")
            if return_details:
                return {'results': [], 'routing_info': config.routing_info, 'query': query}
            return []

        # === Step 6: Cross-encoder reranking (separate step) ===
        rerank_applied = False
        if self.use_rerank and self.reranker and len(results) > 1:
            results = self._rerank_results(query, results, top_k=k)
            rerank_applied = True
        else:
            results = results[:k]

        # === Step 7: Return results ===
        if not return_details:
            return [(chunk, score) for _, chunk, score in results]

        detailed_results = []
        for chunk_idx, chunk, final_score in results:
            detailed_results.append({
                'chunk': chunk,
                'chunk_index': chunk_idx,
                'final_score': final_score,
                'doc_type': chunk.doc_type,
                'pages': f"{chunk.page_start}-{chunk.page_end}",
                'reranked': rerank_applied
            })

        return {
            'results': detailed_results,
            'routing_info': config.routing_info,
            'config': {
                'alpha': self.alpha,
                'rerank_enabled': self.use_rerank,
                'rerank_applied': rerank_applied
            },
            'retrieval_stats': {
                'total_chunks': config.total_chunks,
                'final_returned': len(detailed_results)
            },
            'query': query
        }
